### ISSUE TITLE
Crash reporting dialog is not shown

### ISSUE THREAD

**Issue by pixtur** [tooll3/t3#468]
**Steps to reproduce:**
- Window > Utilities > Simulate Crash

```
System.InvalidOperationException: Thread exception mode cannot be changed once any Controls are created on the thread.
   at System.Windows.Forms.NativeWindow.SetUnhandledExceptionModeInternal(UnhandledExceptionMode mode, Boolean threadScope)
   at T3.MsForms.MsForms.SetUnhandledExceptionMode(Boolean throwException) in C:\Users\pixtur\dev\tooll\t3-main\MsForms\MsForms.cs:line 14
   at T3.Editor.CrashReporting.CrashHandler(SentryEvent sentryEvent, SentryHint hint) in C:\Users\pixtur\dev\tooll\t3-main\Editor\CrashReporting.cs:line 123
   at Sentry.SentryClient.BeforeSend(SentryEvent event, SentryHint hint)
```

![grafik](https://github.com/user-attachments/assets/0ba8e765-d9c3-4f7b-83a7-8a8fe7592089)

**Comment by domportera** [comment]
is this in debug mode or release? is it still a thing?

**Comment by pixtur** [comment]
Couldn't reproduce this.
