### ISSUE TITLE
Crash after Publish input 

### ISSUE THREAD

**Issue by pixtur** [tooll3/t3#472]
**Please complete the following information):**
 - OS: win10
 - Version: 3.10
 - Graphics card and resolution 

**To Reproduce**
1. create open [ThereDemo]
2. Select a [Transform] operaotr
3. In parameter window right click on Translate -> Publish as input
-> Exception

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at T3.Editor.Gui.InputUi.InputArea.PublishAsInput(NodeSelection selection, IInputSlot originalInputSlot, Child symbolChildUi, Input input) in C:\Users\pixtur\dev\tooll\t3-main\Editor\Gui\InputUi\InputValueUi.cs:line 781
   at T3.Editor.Gui.InputUi.InputValueUi`1.<>c__DisplayClass50_0.<DrawParameterEdit>b__6() in C:\Users\pixtur\dev\tooll\t3-main\Editor\Gui\InputUi\InputValueUi.cs:line 496
   at T3.Editor.Gui.Styling.CustomComponents.ContextMenuForItem(Action drawMenuItems, String title, String id, ImGuiPopupFlags flags) in C:\Users\pixtur\dev\tooll\t3-main\Editor\Gui\Styling\CustomComponents.cs:line 338
   at T3.Editor.Gui.InputUi.InputValueUi`1.<>c__DisplayClass50_0.<DrawParameterEdit>g__DrawNormalParameter|2() in C:\Users\pixtur\dev\tooll\t3-main\Editor\Gui\InputUi\InputValueUi.cs:line 468
   at T3.Editor.Gui.InputUi.InputValueUi`1.DrawParameterEdit(IInputSlot inputSlot, SymbolUi compositionUi, Child symbolChildUi, Boolean hideNonEssentials, Boolean skipIfDefault) in C:\Users\pixtur\dev\tooll\t3-main\Editor\Gui\InputUi\InputValueUi.cs:line 159
   at T3.Editor.Gui.Windows.ParameterWindow.DrawParameters(Instance instance, SymbolUi symbolUi, Child symbolChildUi, SymbolUi compositionSymbolUi, Boolean hideNonEssentials, ParameterWindow parameterWindow) in C:\Users\pixtur\dev\tooll\t3-main\Editor\Gui\Windows\ParameterWindow.cs:line 379
   at T3.Editor.Gui.Windows.ParameterWindow.DrawParametersArea(Instance instance, Child symbolChildUi, SymbolUi symbolUi) in C:\Users\pixtur\dev\tooll\t3-main\Editor\Gui\Windows\ParameterWindow.cs:line 233
   at T3.Editor.Gui.Windows.ParameterWindow.DrawContent() in C:\Users\pixtur\dev\tooll\t3-main\Editor\Gui\Windows\ParameterWindow.cs:line 120
   at T3.Editor.Gui.Windows.Window.Draw() in C:\Users\pixtur\dev\tooll\t3-main\Editor\Gui\Windows\Window.cs:line 52
   at T3.Editor.Gui.Windows.Layouts.WindowManager.Draw() in C:\Users\pixtur\dev\tooll\t3-main\Editor\Gui\Windows\Layouts\WindowManager.cs:line 31
   at T3.Editor.Gui.T3Ui.ProcessFrame() in C:\Users\pixtur\dev\tooll\t3-main\Editor\Gui\T3UI.cs:line 122
   at T3.Editor.Gui.WindowsUiContentDrawer.RenderCallback() in C:\Users\pixtur\dev\tooll\t3-main\Editor\Gui\WindowsUiContentDrawer.cs:line 159
   at T3.Editor.App.AppWindow.<>c__DisplayClass38_0.<RunRenderLoop>b__0() in C:\Users\pixtur\dev\tooll\t3-main\Editor\App\AppWindow.cs:line 111
   at SharpDX.Windows.RenderLoop.Run(Control form, RenderCallback renderCallback, Boolean useApplicationDoEvents)
   at T3.Editor.App.AppWindow.RunRenderLoop(Action callback) in C:\Users\pixtur\dev\tooll\t3-main\Editor\App\AppWindow.cs:line 111
   at T3.Editor.Program.Main(String[] args) in C:\Users\pixtur\dev\tooll\t3-main\Editor\Program.cs:line 186
``` 

![image](https://github.com/user-attachments/assets/6fa33971-62ab-4f4c-8053-e29346159509)

**Comment by pixtur** [comment]
With v4.0 this needs to be rethought because backend implementation changed.
